site_name: bpstd
site_description: common std lib
site_author: Henry Huang

repo_url: https://github.com/hhstore/better-py/pkg
edit_uri: https://github.com/hhstore/better-py/pkg/edit/main/docs

theme: readthedocs

markdown_extensions:
  - codehilite

nav:
  - Home: index.md
  - Advanced: advanced.md
  - About:
    - Release Notes: about/changelog.md
    - Contributor Guide: about/contributing.md
    - License: about/license.md
