version: "3"


#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing


################################################################################################


tasks:
  install:
    cmds:
      - pip3 install -r requirements.txt

  dep:add:
    cmds:
      - poetry add django@^3.2
      - poetry add djangorestframework@^3 django-choices
      - poetry add requests geetest pika twilio validators sqlalchemy telegram slackclient
      - poetry add pycoin eth_utils

  dep:search:
    cmds:
#      - poetry search requests
      - poetry search drf

  dep:update:
    cmds:
      - poetry update
      - poetry update package

  dep:install:
    cmds:
      - poetry install

  dep:export:
    cmds:
      - poetry export --output requirements.txt

  dep:show:
    cmds:
      - poetry show


  run:
    cmds:
      - |
        python3 run.py

  run:args:
    cmds:
      - |
        python3 run.py \
          --infile_a=input/1.xlsx \
          --infile_b=input/2.xlsx \
          --outfile=output/out.xlsx
